// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8iPQAtwI6si65qEaIVKBOCJktVikoM84',
    appId: '1:172537611610:web:cec43bbb0c6137d1a29f63',
    messagingSenderId: '172537611610',
    projectId: 'phoneauthflutter-394f4',
    authDomain: 'phoneauthflutter-394f4.firebaseapp.com',
    storageBucket: 'phoneauthflutter-394f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3wHKFxVIjFPgmXOZ5y1yO1kb5UrSAGLQ',
    appId: '1:172537611610:android:545e1ab1f3b2766aa29f63',
    messagingSenderId: '172537611610',
    projectId: 'phoneauthflutter-394f4',
    storageBucket: 'phoneauthflutter-394f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhkpWciR1WuaZvHbPp3wE6qYeFfx2Eo94',
    appId: '1:172537611610:ios:e86a7159dff53e8aa29f63',
    messagingSenderId: '172537611610',
    projectId: 'phoneauthflutter-394f4',
    storageBucket: 'phoneauthflutter-394f4.appspot.com',
    iosClientId: '172537611610-6ge770nsnrlpo3hcaa3ug61uq38sgbs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuth',
  );
}
